
// A rasterization of Ubuntu Mono size 16, with some minor pixel alignment for increased sharpness in the specific resolution.
// The font was selected because it has a reusable generic style and permits both modification and embedding.
// See the official website for full license terms
//   https://www.ubuntu.com/legal/font-licence

static const char* defaultFontAscii =
R"QUOTE(< .,-_':;!+~=^?*abcdefghijklmnopqrstuvwxyz()[]{}|&@#0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ>
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                      [  [                             g[                                              g[                                                                                                                                'y     >
<                       [g             X  X            [f h(            [Z            jx'  q*          j(o.             )X                g            g                f)                                                                                t3     >
<                       Z[             R  R           !Zt 0R          !6UZQj         dR79 bM,         &ZZZ7             xU               {Xe          hX]               vS                                                                                Fh     >
<                       Z[             D  D           cZk 9H          DU@]Al         y|_V Fm          V8-5W             qM              yXj            pZy            3|rFmEc                                                                            ^O      >
<                       Z)             k  k          [ZZZZZZ[         X&             y|_VqB           N2 C5             hD             ^Xy              {X^           &GSXNAg           Z                                                                [{      >
<                       Wy                           gAZ}[VGg         FX2h           dR7DO?           rYIB'                            #R.              ,S#            'EIq             Z                                                                O?      >
<                       Qs                            )X  X)          +AZZG=          jx22xi          &UXe)M                           N3                4M            A9cXf            Z                              [[[g                             fG       >
<                       Gj                            0R !Zs            =)VF           ?OE7Rd        aZc6UAA                           X]                ]X            ^~ h          ZZZZZZZ                           ZZZ[                             1v       >
<                                                    [ZZZZZZ[             &W           BqV-&y        xZ..9Zp                           U&                |U                             Z                                                              ,S:       >
<                      ,ue                           gRK[6Z#g         92[@UH          mE V-&y        uZu=9Z#                           DF                FC                             Z               kj                              kk             o8        >
<                      vZS                            R0 tZ!          }OXZHc         ,Mb A7Rd        :QZZNzX!                          sZc              aZr                             Z               UU                              UU             Am        >
<                      eS6                            (h f[             [Z           *q  :xj          ;vu'-[b                          .IK_            ,HI.                                             )M                              kk            ;R.        >
<                                                                       [Z                                                              =QG;          'CR=                                             @Ri                                            x#         >
<                                                                                                                                        ~Da          *D~                                              p+                                             Ie         >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<      ^ww^              vg            fzt;           ,ozs'              ~[g          '[[[[g             aub          [[[[[[g          ^wyc            =xu!                                                                                            fxzh      >
<     mXZZXm           '5Z[           #ZZZR!          IZZZQ;            ;NZ[          *ZZZZ[           !CZZy          ZZZZZZ[         mXZZZx          eVZZT^                                                                                          pZZZZ|     >
<    ,SG++GR,         hS9Z[           #j,wZv          g+.pZv            E#Z[          eZ?             -LMn;               sU=         OG;+GT          DO+?S4                                                                                          ;g-!GV     >
<    jZi  iZj         !g Z[              .Zw             'Zt           }A Z[          kZ-             xU!                ~Vt          W0  &O          W}  1R            kk              kk                jAl                         B);                 0I     >
<    wZ:EE:Zw            Z[              jU!            ]IB,          fQ: Z[          sZUGr           FROWA;             3J           AX]qRk          U2  ]X            UU              UU             ,tKOw-        [ZZZZZZ[         e6V2b              rRa     >
<    (Z FG.Z(            Z[             ~Qm             ZZ3:         .Ln  Z[          f}5RZw          UQ&1X5            ~Xp           +UZZL~          6X1&PU            kk              kk            {SGo                              =&UCd           uWd      >
<    wZ:  :Zw            Z[            +Mr              .eOB         rV[[[ZDg            ,GP          X[  3T            ]S.           {K?yVC          !BWPRH                                          VOj                                ;@Zy           U0       >
<    jZi  iZj            Z[           -Kv                 {X         [ZZZZZZ[             }X          R1  |W            M0            S{  &W             :T]                                          :zQKs,         [ZZZZZZ[          *2V8h                     >
<    ,SG++GS,            Z[           {8              i: aMM              Z[          i: cOH          6S?+OD           ^Zn            TG;!HP           'lIR;            kk             :w_              .oGRh                         6U&=             :x:       >
<     mXZZXn           ZZZZZ[         RZZZZZ          RZZZWl              Z[          RZZZUh          *UZZVe           pZ=            zZZZZt          (ZZKa             UU             xZw                 e+                         i_               xZx       >
<      ^ww^            [[[[[g         )[[[[[          !s(s+               [g          +s(s;            +vx=            f[              eyyc           eve               kk             !Ro                                                             :x:       >
<                                                                                                                                                                                     gFA                                                                        >
<                                                                                                                                                                                     ?k                                                                         >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<      ,ozl            i[).           pz(p_             gywc          ozyj            g[[[[[          g[[[[[            hyxf         g[    [g         g[[[[[           [[[[g          [g  mv          g[              tt  tu          [t  g[           ^ww=      >
<     !LZZZ7           GWZi           ZZZZQ;          :EZZZZo         ZZZZL=          [ZZZZZ          [ZZZZZ          :EZZZZo        [Z    Z[         [ZZZZZ           ZZZZ[          Z[ ~Vu          [Z              OV,,WR          ZX+ [Z          nXZZXl     >
<     7Tf,[Zh         ;Y&V&           Z[.rZv          9Wu_'k;         Z[.jRI          [Z              [Z              9Xv'-i'        [Z    Z[           [Z                Z[          Z[ AG           [Z              XQhhQZ.         ZU[ [Z         ,SE;+GR.    >
<    !Yy  'Zz         oZhBK           Z[ 'Zt         *Zz              Z[  oZe         [Z              [Z             *Z)             [Z    Z[           [Z                Z[          Z[tV?           [Z             :Z1{{0Z+         Z1O [Z         jZh  iZi    >
<    mZ*?GXZ[         1W,(Z;          ZD{IA,         uZ+              Z[  :Zv         [Z[[[g          [Z[[[g         uZ+             [Z[[[[Z[           [Z                Z[          Z5Vu            [Z             ?ZmGGlZb         Z[9i[Z         wZ_  'Zw    >
<    wZ,GT}Z[         ME gZo          ZZZY4:         (Z               Z[   Z(         [ZZZZ[          [ZZZZ[         (Z    [g        [ZZZZZZ[           [Z                Z[          ZXZj            [Z             gZ+RR!Zh         Z[m2[Z         (Z    Z(    >
<    (Z X| Z[        !Z[ ,X@          Z[ *LD         uZ!              Z[  ;Zv         [Z              [Z             uZ!   Z[        [Z    Z[           [Z                Z[          Z{8V*           [Z             lZ;pq:Zl         Z[.M{Z         wZ_  'Zw    >
<    vZ;RA,Z[        nZZZZZI          Z[  {X         dZw              Z[  pZe         [Z              [Z             dZv   Z[        [Z    Z[           [Z               _Zz          Z[,HL,          [Z             qZ'  -Zq         Z[ #FZ         jZg  iZi    >
<    hZl(ZZZ[        &X[[[BY'         Z[ aMM          GVr--g!         Z].iRI          [Z              [Z              GVq,'Z[        [Z    Z[           [Z            g!-{Zm          Z[ ?W]          [Z             uZ,  ,Zu         Z[ gYZ         ,SE;+GR.    >
<    .RE i(u~        GE   hZj         ZZZZWm          =MZZZZq         ZZZZM^          [ZZZZZ[         [Z              ~LZZZZ[        [Z    Z[         [ZZZZZ          KZZZH.          Z[  }V!         [ZZZZZ[        yZ.   Zx         Z[  RZ          nXZZXm     >
<     tZ7?.!         zj   ,[e         pz(s+            .lzwe          ozyk.           g[[[[[g         g[               .lzym'        g[    [g         g[[[[[          'r(o,           [g  :[c         g[[[[[g        f[    [f         [g  n[           ?ww^      >
<      )XZZT                                                                                                                                                                                                                                                     >
<       ^uzm                                                                                                                                                                                                                                                     >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                     y'                                                         >
<     nx)wc            ^ww=           oy(s;            bxxg           [[[[[[g         [g  g[         zj   ,[e        i)    (i        a[:  :[a        c[-   lx         [[[[[[           g[[[g          3t              g[[[g             ez                       >
<     ZZZZZ2          mXZZXl          ZZZZUf          tZZZZq          ZZZZZZ[         Z[  [Z         EE   eZi        }X    V}        -R&  &R-        ~Yu  ,S0         ZZZZZZ           [Z[[g          hF              g[[Z[             LYp                      >
<     Z[ '{Zj        ,SE;+GR.         Z[ aNG          QF+,g;            [Z            Z[  [Z         [X-  zW,        }X    V{         tX==Xt          9L  sZa            -O@           [Z              O=                Z[            tOwO.                     >
<     Z[  ,Zz        jZh  iZh         Z[  {W          W2                [Z            Z[  [Z         fZn  BC         }X    V]          K55K           fZq M9             0O-           [Z              {[                Z[           ,Rq Lw                     >
<     Z[  aZt        wZ_  'Zw         Z[  4R          6Z6g              [Z            Z[  [Z          T4 ,Vx         }X nm V)          lZZl            COuZc            gZj            [Z              ?O                Z[           (I  mS'                    >
<     ZD[#RT;        (Z    Z(         ZD]8Z}          -0XZC!            [Z            Z[  [Z          5U,jZ?         }X PO V(           QQ             dZX6            .M6             [Z               Hf               Z[           6i   9f                    >
<     ZZZUAb         xZ_  'Zw         ZZZZ7.            ![XA            [Z            Z[  [Z          pZm@M          }XfCCfVy          oZZp             6Z^            zV+             [Z               v1               Z[                                      >
<     Z[             mZg  iZi         Z[ 2J.              @W            [Z            V@  #V          'X8P}          }X&uu&Vw         -Q10R-            [Z            !V)              [Z               :S,              Z[                                      >
<     Z[             :WE;+GR,         Z[ :Tw          i~ ~GR            [Z            GQ~~QG           BZZc          }XP!;PWu         )U;:U]            [Z            0R,              [Z                8o              Z[                                      >
<     Z[              yZZZXm          Z[  )S_         MZZZZt            [Z            lXZZXl           tZN           }ZF  DZs        'U]  {V:           [Z            XZZZZZ           [Z                mA              Z[                                      >
<     [g               iVH?           [g  '[b         -nzw*             g[             *xx*            :[l           i[h  g[b        b['  :[b           g[            [[[[[[           [Z                .R;             Z[                                      >
<                       [ZG}                                                                                                                                                           [Z                 #w             Z[                                      >
<                        lAB                                                                                                                                                           [ZZZ[              eI          [ZZZ[                          ZZZZZZZZ    >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<       1c                            oe                                  ?v                            -p(s+                         oe                                              oe              [[[g                                                       >
<       wK,                           Z[                                  [Z                           -LZZZR                         Z[               kUl              kUl           Z[              ZZZ[                                                       >
<        @h                           Z[                                  [Z                           rZu,;i                         Z[               lUl              lUl           Z[                Z[                                                       >
<                                     Z[                                  [Z                           )Z                             Z[                                              Z[                Z[                                                       >
<                      BUXF*          ZKRWB?           mGWU9          ?BWRKZ          '#RWGf          ZZZZZZ          ~6UXRB          ZQUV8;          ZZZ[             ZZZZ           Z[ !Q#            Z[           oOXM2UE-         BQWU6;          !5UU5!     >
<                      B}#WG          ZU#&TP,         nZM||6         ,PT&#UZ          GV1|PU;         [DZ[[[         ,NU@[HZ          ZK}3Z5          [[Z[             [[DZ           Z['I8             Z[           [Z}OX5Zs         ZH]3Z6         .KU@@VK.    >
<                         &X          Z[  iZn         IK,            nZi  [Z         kZi  =Zs          [Z            oZh  [Z          Z[  7T            Z[               [Z           Z&HA,             Z[           [Z ]X Z)         Z[  6U         lZl  lZl    >
<                     *CUWTZ          Z[  ,Zz         W{             zZ,  [Z         zZZZZZZ)          [Z            (Z.  [Z          Z[  ]Z            Z[               [Z           ZXR-              Z[           [Z [Z Z[         Z[  [Z         zZ.  .Zz    >
<                     MB; |Z          Z[  +Zu         T1             uZ+  [Z         uZ~               [Z            sZe  [Z          Z[  [Z            Z[               [Z           Z|8D_             Z[           [Z g[ Z[         Z[  [Z         uZ!  +Zu    >
<                     VA: {Z          Z| ~9X=         4Wr--g         =X9+ }Z         =XEb 'h           [Z            ;UR&@PZ          Z[  [Z            UB,d             [Z           Z[ 3H-            UB,d         [Z    Z[         Z[  [Z         =X5::6X=    >
<                     &ZZZZZ          ZZZZXv          !LZZZU          vXZZZZ          rWZZZU           [Z             eGXRMZ          Z[  [Z            5ZZU             [Z           Z[  AB            5ZZU         [Z    Z[         Z[  [Z          wYZZYw     >
<                      gwztj          fu(v^            .mzvb           ^v(uf           !r(u*           g[                 5T          [g  g[            ,szd             |X           [g  ;[?           ,syd         g[    [g         [g  g[           *xw*      >
<                                                                                                                     B#[6Z4                                          i6|UG                                                                                      >
<                                                                                                                     6SXR0_                                          fIXLc                                                                                      >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                      .o([             g[             [(o.                                      >
<                                                                      ?v                                                                                                              5S}[             [Z             [}T5                                      >
<                                                                      [Z                                                                                                              V|               [Z               |V                                      >
<                                                                      [Z                                                                                                              Z[               [Z               [Z                                      >
<    oKVXIo           oIXVKn          hAQXWH           ;s(ue          ZZZZZZ          Z[  [Z         qZ?  ^Zq        wZ,  ,Zw        *Vs  rV*         O4  ~Zt         [ZZZZZ           Z[               [Z               [Z                                      >
<    [Z|]IZo         oZI{|Z[          [Z5{[t          ^TZZZR          [DZ[[[          Z[  [Z         !Zw  vZ!        oZ=??=Zn         tV??Vt          2R  pZb         g[[[RJ           Zz               [Z               yZ                                      >
<    [Z  .II         II.  X[          [Z              yZe ;h           [Z             Z[  [Z          HD  DH         dZg))hZb          6II6           nZd #V             {O!          jZf               [Z               dZi          1WEl-An                    >
<    [Z   {W         X{   X[          [Z              fXR#g            [Z             Z[  [Z          )X;;Xz         'ZrAAsZ-          'SS'           -W| KC            tU*          [Z0                [Z                1Z[        jU|HZZU+                    >
<    [Z   1T         T2   X[          [Z               f9XZB-          )Z             X&  [Z          ?ZvvZ=          R@AB@O           pXOp            6Q!Z(           gXl            iZg               [Z               jZi         =h  hza                     >
<    [Zd.gU6         5Vg.dY[          [Z                 -tZv          wZk.e          KP= |Z           GIIF           BU(]U7          aVwdUa           lZ8Ze          ;R&              Z(               [Z               )Z                                      >
<    [ZZZZR=         =RZZZZ[          [Z              nF|[7Zq          ?XZZU          oYZZZZ           tZZs           {ZchZ(         ,K9  1K,           PZR           (ZZZZZ           Z[               [Z               [Z                                      >
<    [Zizt'           'szhZ[          g[              fFVXO{            *xyc           ax(uf           -[[-           b( .[?         *[;  ;[*           4Z0           g[[[[[           Z[               [Z               [Z                                      >
<    [Z                   Z[                                                                                                                          (2ZU~                            R9,              [Z              ,9R                                      >
<    [Z                   Z[                                                                                                                          KXGd                             mNYZ             [Z             ZXMl                                      >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                       [g                                                                                                                                                       >
<                                                       cxyc                         b[_   mv           Z[             +vzl,          MqrM                             r(m                                                                             ZZZZ      >
<                                       [Z             qZZZR                         !Xu  :Uy           Z[            ^UZZZt          q==q                             }{Rk                                                                            [[[[      >
<                                       [Z             KM~_g         ,f   ,e          5J  |Q,           Z[            yZb.d~                                           jzC)                                                                                      >
<                      FO             +5UZQk           X}            fWCVMIA          dZj^Xr            Z[            kZ9o,                           ;4UU5;          rM]E[            -l -l                                          ;4UU5;                     >
<                      FO            .LY7]6l           Z[             D&-dRf           CFAG             Z[            -IXZRk                          I|::|I          sK[E[            {E {E                                          I|::|I                     >
<                                    mZu             [ZZZZZ[          V,  }y          [9ZZ7[g                         AA-oQR                         lE+MK El          l(xa           +Vh+Vi          ZZZZZZZ          g[[[          lEyXOcEl                    >
<                      ~r            zZ-             g[ZC[[g          Oa  7q          ZZZZZZ[                         W9. &O                         z{x1, {z                         nX'nX:               [Z          [ZZZ          z{[DIs{z                    >
<                      nK            wZ-              ,Zx            ,JR|9Zq            [Z              [g            2ZR3Kc                         u#nMz 0u                          I) I[               [Z                        u#[HG 0u                    >
<                      vT            aZu              +Zo            eAgyqr6          ZZZZZZ[           Z[             qDXM;                         =S~qt~R~                          i8 i8               [Z                        =SqgliR~                    >
<                      (X             )X7]4r          gZZZZZ[                         [[DZ[[g           Z[               *Zx                          vR&&Rt                                               gg                         vR&&Rt                     >
<                      [Z              bBZx+          a[[[[[g                           g[              Z[            A#[8Zo                           ?ww^                                                                            ?ww^                      >
<                      [Z               [Z                                                              Z[            #RXR}                                                                                                                                      >
<                      [Z               g[                                                              Z[                                                                                                                                                       >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<      -uu-                                                             d1                                                                                                                                                                                       >
<      988A                                            axx=            ,Lw                            .jGHF                                             hg             !vv!                           -y   n*         -z   n*         ~wv-  n*                   >
<      X--X             2              cMV|            A&#P            h@                            ^MZZSR                                            7WZ            !R11Q!                         hOZ  =K,        hOZ  =K,         ^[Jw =K,                   >
<      988A             Z              ;b+V             [67                                          CZZZ I                                            i]Z            w1  1w                         ~^Z  Ak         ~^Z  Ak           ZZf Al                    >
<      ,uu,             Z                C{             ]CE                           Z[  wZ         WZZZ I                                              Z            w1  1v          _h f!            Z l9            Z l9           *[Kul9            kUk      >
<                    2ZZZZZ2            B)             h.*V                           Z[  wZ         TZZZ I                                              Z            !R11Q!          dV!#B            [,K=            [,K=           ?zs_L=            lUl      >
<                       Z              nQEE            DXRt                           Z[  wZ         1ZZZ I             :x:                            ZZZZ            !ww!            C#-My            [[              [[               [[                      >
<                       Z                                                             Z[  wZ         ,|RZ I             wZw                                                            }K 2F           =K,i[           =K:tt.           =L,i[           h[       >
<                       2                                                             Z&  wZ            Z I             :x:                                                           -TmhU=           9l+BZ           9lh3Iv           9m+BZ           IH       >
<                                                                                     ZO~ (Z            Z I                                                                           hA 6q           lA 4dZ          lA  :4^          lA 4dZ          4I+       >
<                                                                                     ZZZZZZ            Z I                                                                                          ,K= ZZZ[        ,K= cK}g         ,K^ ZZZ[        &I-        >
<                    2ZZZZZ2                                                          Z|w(te            Z I                             =8                                                           *n    [         *n  h||i         *n    [         V&         >
<                                                                                     Z)                Z I                            ,gHi                                                                                                           KW0}Eh     >
<                                                                                     Z[                Z I                            pWRh                                                                                                           aEWU9*     >
<      b2               d1                                                                                                              1c               d1             .c                              1c               3b              .c                      >
<      :Mr             ,Lw              g6            =MO&6            MqrM            =xn                                              wK,             ,Lw             6Ue            qM Mq            wK,             rM:              6Ue           MqrM      >
<       ?7             h@              bO83           ?=ey~            q==q            R~2t                                              @h             h@             h#c6            =q q=             @h             7?              h#c6           q==q      >
<      i[).            i[).            ;? f            i[).            i[).            I2Mk            t[[[[            ;rzo_         g[[[[[          g[[[[[          g[[[[[          g[[[[[          g[[[[[          g[[[[[           g[[[[[         g[[[[[     >
<      GWZi            GWZi            ~ZZ1            GWZi            GWZi            KSZj           ,WYZZZ           rVZZZL         [ZZZZZ          [ZZZZZ          [ZZZZZ          [ZZZZZ          [ZZZZZ          [ZZZZZ           [ZZZZZ         [ZZZZZ     >
<     ;Y&V&           ;Y&V&            vZHR           ;Y&V&           ;Y&V&           ~Z)U#           iZJZ            dXDa.^i         [Z              [Z              [Z              [Z                [Z              [Z               [Z             [Z       >
<     oZhBK           oZhBK            ARqZc          oZhBK           oZhBK           tZe9M           ]Z#Z            6R-             [Z              [Z              [Z              [Z                [Z              [Z               [Z             [Z       >
<     1W,(Z;          1W,(Z;          .V3!Zy          1W,(Z;          1W,(Z;          4V.zZ+          EO[Z[g          R1              [Z[[[g          [Z[[[g          [Z[[[g          [Z[[[g            [Z              [Z               [Z             [Z       >
<     ME gZo          ME gZo          fZr NA          ME gZo          ME gZo          RC fZq         .W4[ZZ[          X]              [ZZZZ[          [ZZZZ[          [ZZZZ[          [ZZZZ[            [Z              [Z               [Z             [Z       >
<    !Z[ ,X@         !Z[ ,X@          (Z= 3U         !Z[ ,X@         !Z[ ,X@         =ZF[}Z1         cZBDZ            S0              [Z              [Z              [Z              [Z                [Z              [Z               [Z             [Z       >
<    nZZZZZI         nZZZZZI          AX[[BZc        nZZZZZI         nZZZZZI         qZZZZZK         tZZZZ            BR,             [Z              [Z              [Z              [Z                [Z              [Z               [Z             [Z       >
<    &X[[[BY'        &X[[[BY'         UZZZZZw        &X[[[BY'        &X[[[BY'        #W,  [Z'        1V [Z            lZA*.~h         [Z              [Z              [Z              [Z                [Z              [Z               [Z             [Z       >
<    GE   hZj        GE   hZj        *Zs   P6        GE   hZj        GE   hZj        HD   hZi        IC [ZZZ           [YZZZN         [ZZZZZ[         [ZZZZZ[         [ZZZZZ[         [ZZZZZ[         [ZZZZZ          [ZZZZZ           [ZZZZZ         [ZZZZZ     >
<    zj   ,[e        zj   ,[e        sZ=   3Q        zj   ,[e        zj   ,[e        zj   ,[e        (j g[[[            ^|Gq:         g[[[[[g         g[[[[[g         g[[[[[g         g[[[[[g         g[[[[[          g[[[[[           g[[[[[         g[[[[[     >
<                                                                                                                       ,gHi                                                                                                                                     >
<                                                                                                                       pWRh                                                                                                                                     >
<                                       1c               3b             c.                                                                             b2                3b             c.                               3b                                      >
<                     =MO&6             wK,             rM:            eU6            =MO&6           qM Mq                                            :Mr              rM:            eU6             MqrM             rM:                                      >
<                     ?=ey~              @h             7?             6c#h           ?=ey~           =q q=                                             ?7              7?             6c#h            q==q             7?                             bzv=      >
<     pzyk.           [t  g[           ^ww=            ^ww=            ^ww=            ^ww=           .nzm                             *yx04          [g  g[          [g  g[          [g  g[          [g  g[         c[-   lx          [g             nYZZV*     >
<     ZZZZM^          ZX+ [Z          nXZZXl          nXZZXl          nXZZXl          nXZZXl         ,FZZZE.                          oXZTZ4          Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z         ~Yu  ,S0          Z[,            KM;bZz     >
<     Z],kRI          ZU[ [Z         ,SE;+GR.        ,SE;+GR.        ,SE;+GR.        ,SE;+GR.        xZp,sZw                         ,SF;tZU,         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          9L  sZa          ZZZWCf         X| sXd     >
<     Z[  pZe         Z1O [Z         jZh  iZi        jZh  iZi        jZh  iZi        jZh  iZi        GE   FF          d9- -9d        jZi L7Zk         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          fZq M9           ZC(@RW^        Z[wVm      >
<    [ZD[ :Zv         Z[9i[Z         wZ_  'Zw        wZ_  'Zw        wZ_  'Zw        wZ_  'Zw        U|   &T          ,EG?GE,        wZ'kZcZw         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z           COuZc           Z[  ^Zx        Z[V@       >
<    ZZZZ  Z(         Z[m2[Z         (Z    Z(        (Z    Z(        (Z    Z(        (Z    Z(        X[   [X           'IZI'         (Z CC Z(         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z           dZX6            Z[  'Zx        Z[4X}'     >
<     Z[  :Zv         Z[.M{Z         wZ_  'Zw        wZ_  'Zw        wZ_  'Zw        wZ_  'Zw        U|   &T           'IYI'         xZcZj:Zw         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z            6Z^            Z[ +3Zd        Z[ mNQ+    >
<     Z[  oZe         Z[ #FZ         jZg  iZi        jZg  iZi        jZg  iZi        jZg  iZi        GE   FF          ,EG^GE,        nZ6K jZi         V@  #V          V@  #V          V@  #V          V@  #V            [Z             ZZZZZ}         Z[  !Zy    >
<     Z[.iRI          Z[ gYZ         ,SE;+GR.        ,SE;+GR.        ,SE;+GR.        ,SE;+GR.        yZo.sZw          d9- -9d        'WZs!GS,         GQ~~QG          GQ~~QG          GQ~~QG          GQ~~QG            [Z             ZD)u*          Z[d,hZu    >
<     ZZZZM^          Z[  RZ          nXZZXm          nXZZXm          nXZZXm          nXZZXm         ,GZZZE,                          6ZRZXq          lXZZXl          lXZZXl          lXZZXl          lXZZXl            [Z             Z[             Z[SZZS!    >
<     pzyk.           [g  n[           ?ww^            ?ww^            ?ww^            ?ww^           .ozn.                           43zya            *xx*            *xx*            *xx*            *xx*             g[             [g             [gdyu!     >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<       1c               3b             .c                                                                                             b2                3b             .c                             b2               d1               c.                      >
<       wK,             rM:             6Ue            [VA3j           MqrM             ]}e                                            :Mr              rM:             6Ue            MqrM            :Mr             ,Lw              eU6           qM Mq      >
<        @h             7?             h#c6            j:so            q==q             }~v                                             ?7              7?             h#c6            q==q             ?7             h@               6c#h          =q q=      >
<                                                                                       ev,                                                                                                                                                                      >
<      BUXF*           BUXF*           BUXF*           BUXF*           BUXF*           BUXF*         oUJ?IOc           :0RXMk         '#RWGf          '#RWGf          '#RWGf          '#RWGf          ZZZ[            ZZZ[             ZZZ[           ZZZ[       >
<      B}#WG           B}#WG           B}#WG           B}#WG           B}#WG           B}#WG         o|RS9RB          .IX5]6k         GV1|PU;         GV1|PU;         GV1|PU;         GV1|PU;         [[Z[            [[Z[             [[Z[           [[Z[       >
<         &X              &X              &X              &X              &X              &X           [Z;|U          lZq            kZi  =Zs        kZi  =Zs        kZi  =Zs        kZi  =Zs           Z[              Z[               Z[             Z[       >
<     *CUWTZ          *CUWTZ          *CUWTZ          *CUWTZ          *CUWTZ          *CUWTZ         oUUZZZZ          zZ,            zZZZZZZ)        zZZZZZZ)        zZZZZZZ)        zZZZZZZ)           Z[              Z[               Z[             Z[       >
<     MB; |Z          MB; |Z          MB; |Z          MB; |Z          MB; |Z          MB; |Z         O2yZ'            wZ+            uZ~             uZ~             uZ~             uZ~                Z]              Z]               Z]             Z]       >
<     VA: {Z          VA: {Z          VA: {Z          VA: {Z          VA: {Z          VA: {Z         V3jZ},e          aZB?.=^        =XEb 'h         =XEb 'h         =XEb 'h         =XEb 'h            UE_!;           UE_!;            UE_!;          UE_!;    >
<     &ZZZZZ          &ZZZZZ          &ZZZZZ          &ZZZZZ          &ZZZZZ          &ZZZZZ         7ZZUZZU           (ZZZZw         rWZZZU          rWZZZU          rWZZZU          rWZZZU            1ZZZv           1ZZZv            1ZZZv          1ZZZv    >
<      gwztj           gwztj           gwztj           gwztj           gwztj           gwztj         ,vr-pze            *J[m,          !r(u*           !r(u*           !r(u*           !r(u*            .o(p-           .o(p-            .o(p-          .o(p-    >
<                                                                                                                       -@A                                                                                                                                      >
<                                                                                                                       KX7                                                                                                                                      >
<                                                                                                                                                                                                                                                                >
<                                                                                                                                                                                                                                                                >
<       e!                              1c               3b             c.                                                                             b2                3b             .c                               d1            oe                        >
<       |T[Gm         =MO&6             wK,             rM:            eU6            =MO&6           qM Mq                                            :Mr              rM:             6Ue            MqrM             ,Lw            Z[              qM Mq     >
<      gKXXo,         ?=ey~              @h             7?             6c#h           ?=ey~           =q q=                                             ?7              7?             h#c6            q==q             h@             Z[              =q q=     >
<      +j?Yo                                                                                                                               b'                                                                                          Z[                        >
<      bznF7          BQWU6;          !5UU5!          !5UU5!          !5UU5!          !5UU5!          qLXKq             UU            ;4UV9Md         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          O4  ~Zt          ZKPWB^         O4  ~Zt    >
<     jXZZXP          ZH]3Z6         .KU@@VK.        .KU@@VK.        .KU@@VK.        .KU@@VK.        oZE]FZo            kk           .JV#&VP.         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          2R  pZb          ZS#&UO,        2R  pZb    >
<     FQ~;BW          Z[  6U         lZl  lZl        lZl  lZl        lZl  lZl        lZl  lZl        IG   HI                         lZm uJZm         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          nZd #V           Z[  jZn        nZd #V     >
<     V&  ]W          Z[  [Z         zZ.  .Zz        zZ.  .Zz        zZ.  .Zz        zZ.  .Zz        X{   {X         gZZZZZZg        zZ.qG'Zz         Z[  [Z          Z[  [Z          Z[  [Z          Z[  [Z          -W| KC           Z[  .Zz        -W| KC     >
<     W|  4M          Z[  [Z         uZ!  +Zu        uZ!  +Zu        uZ!  +Zu        uZ!  +Zu        S0   1S                         vZsH'+Zu         X&  [Z          X&  [Z          X&  [Z          X&  [Z           6Q!Z(           Z[  !Zv         6Q!Z(     >
<     CP+bU@          Z[  [Z         =X5::6X=        =X5::6X=        =X5::6X=        =X5::6X=        2Vi.jV2            kk           ?ZU=;7X=         KP= |Z          KP= |Z          KP= |Z          KP= |Z           lZ8Ze           Z5''3Z*         lZ8Ze     >
<     dVZZQ+          Z[  [Z          wYZZYw          wYZZYw          wYZZYw          wYZZYw         ;KZZZK;            UU           ,PZZZXu          oYZZZZ          oYZZZZ          oYZZZZ          oYZZZZ            PZR            ZZZZZ|           PZR      >
<      =xu:           [g  g[           *xw*            *xw*            *xw*            *xw*           ,ozo,                          g|byw?            ax(uf           ax(uf           ax(uf           ax(uf            4Z0            Z#uzf            4Z0      >
<                                                                                                                                                                                                                     (2ZU~            Z[             (2ZU~      >
<                                                                                                                                                                                                                     KXGd             Z[             KXGd       >
)QUOTE";

