# See ci.yml.tabs for the properly indented version if you are having trouble seeing the indentation in this file.
# This version is only for Github to parse.
name: DFPSR tests
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x86_32, x86_64, arm, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cd ./Source
          ./test.sh
